services:
  eaglercraft:
    build: .
    container_name: eaglercraft-paper
    ports:
      - "25565:25565"
    volumes:
      - ./data:/server
    restart: unless-stopped

  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: eaglercraft-proxy
    depends_on:
      - eaglercraft
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
